### ISSUE TITLE
Doesn't seem to work for me.

### ISSUE THREAD

**Issue by jiecerbo** [web2easy/OctoberCMS-Zooming-Images-Plugin#1]
Tried using this plugin in my existing project but it doesn't seem to work. I have followed the instructions which seems to be quite clear but still nothing happens, even the cursor doesn't change to a magnifying glass when I hover over the image. I think i'm missing some css and js files. What css and js files should I include in my project?

**Comment by alex-lit** [comment]
@jiecerbo hi, have you add the `{% styles %}` and `{% scripts %}` tags to your layouts?

**Comment by jiecerbo** [comment]
Yup, I have added both the tags in my partial page. Is there any specific location inside the page where I should put those tags?

**Comment by alex-lit** [comment]
Try to add them to layout, not partial.
