### ISSUE TITLE
Still work in october cms now ?

### ISSUE THREAD

**Issue by thaivanluat** [web2easy/OctoberCMS-Zooming-Images-Plugin#2]
Hello, i am using this plugin and i try to following the instructions but seem like it only work when i put some img tag on my layout and that img can be zoom , but when i add data-action zoom on img in blog post partial, it doesnt zoom. I dont know why ? Can you help me.

**Comment by alex-lit** [comment]
HI, have you added a tags `{% component 'zoomingImages' %}` and `{% scripts %}` to your blog layout?

**Comment by thaivanluat** [comment]
Yes, i add ` {% component 'zoomingImages' %} ``{% scripts %}` and `{% styles %}`
in my layout. and in my partial i add a img tag like instruction and it work but with img in blog post, it doesnt (all have data-action='zoom').

**Comment by alex-lit** [comment]
Can you provide a link to your application?
